# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'basicForSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for basicForSwift
  
#  接口请求
  pod 'Moya/RxSwift'
#  pod 'Alamofire'
#  数据解析
#  pod 'SwiftyJSON'
  pod 'HandyJSON'
#  loading
  pod 'SVProgressHUD'
#  键盘组件
  pod 'IQKeyboardManagerSwift'
#  页面布局组件
  pod 'SnapKit'
#  网络图片加载
  pod 'Kingfisher'
#  轮播组件
  pod 'SDCycleScrollView'
#  刷新组件
  pod 'MJRefresh'
#  分类组件
  pod 'JXSegmentedView'
  
  pod 'UITextView+Placeholder'
  

end
